[package]
description = "Vast WASM Test Run"
name = "pwasm-run-test"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
vast-types = "0.8.0"
vastjson = { path = "../../../json" }
vm = { path = "../../vm" }
wasm = { path = "../" }
clap = "2.24"
env_logger = "0.5"
rustc-hex = "1"

[features]
default = ["vast-types/std"]
