[package]
description = "Vast Keys Generator CLI"
name = "vastkey-cli"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
docopt = "1.0"
env_logger = "0.5"
vastkey = { path = "../" }
panic_hook = { path = "../../../util/panic-hook" }
vast-crypto = { version = "0.4.2", features = ["publickey"] }
vast-wordlist="1.2"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
threadpool = "1.7"

[[bin]]
name = "vastkey"
path = "src/main.rs"
doc = false
