[package]
description = "Vast engine specification"
name = "spec"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
account-state = { path = "../account-state" }
authority-round = { path = "../engines/authority-round" }
basic-authority = { path = "../engines/basic-authority" }
builtin = { package = "vastcore-builtin", path = "../builtin" }
bytes = { package = "vast-bytes", version = "0.1.0" }
clique = { path = "../engines/clique" }
common-types = { path = "../types" }
engine = { path = "../engine" }
vastash = { path = "../../vastash" }
vastash-engine = { path = "../engines/vastash" }
vast-types = "0.8.0"
vastjson = { path = "../../json" }
evm = { path = "../evm" }
executive-state = { path = "../executive-state" }
hash-db = "0.15.0"
instant-seal = { path = "../engines/instant-seal" }
journaldb = { path = "../../util/journaldb" }
keccak-hash = "0.4.0"
kvdb-memorydb = "0.3.1"
log = "0.4.8"
machine = { path = "../machine" }
null-engine = { path = "../engines/null-engine" }
pod = { path = "../pod" }
rlp = "0.4.2"
trace = { path = "../trace" }
trie-vm-factories = { path = "../trie-vm-factories" }
vm = { path = "../vm" }

[dev-dependencies]
vastcore = { path = "..", features = ["test-helpers"] }
env_logger = "0.5"
tempdir = "0.3.7"
