[package]
name = "blooms-db"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Vast Technologies <admin@vast.io>"]
edition = "2018"

[dependencies]
vastbloom = "0.8.0"
parking_lot = "0.9"

[dev-dependencies]
criterion = "0.3"
tempdir = "0.3"

[[bench]]
name = "blooms"
harness = false
