[package]
description = "WASM Interpreter"
name = "wasm"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
byteorder = "1.0"
vast-types = "0.8.0"
log = "0.4"
vast-wasm = "0.31"
libc = "0.2"
pwasm-utils = "0.6.1"
vm = { path = "../vm" }
wasmi = "0.3.0"

[dev-dependencies]
env_logger = "0.5"
