[package]
description = "Vast Key Management CLI"
name = "vaststore-cli"
version = "0.1.1"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
docopt = "1.0"
env_logger = "0.5"
num_cpus = "1.6"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
parking_lot = "0.9"
vaststore = { path = "../" }
vastkey = { path = "../../vastkey" }
vast-crypto = { version = "0.4.2", features = ["publickey"] }
dir = { path = '../../../util/dir' }
panic_hook = { path = "../../../util/panic-hook" }

[[bin]]
name = "vaststore"
path = "src/main.rs"
doc = false

[dev-dependencies]
tempdir = "0.3"
