[package]
name = "memory-cache"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]
description = "An LRU-cache which operates on memory used"
license = "GPL3"

[dependencies]
vast-util-mem = "0.3.0"
lru-cache = "0.1"
