[package]
description = "Vast Keys Generator"
name = "vastkey"
version = "0.4.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
edit-distance = "2.0"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
vast-crypto = { version = "0.4.2", features = ["publickey"] }
vast-wordlist = "1.3"
