[package]
name = "pod"
description = "State/Account system expressed in Plain Old Data."
authors = ["Vast Technologies <admin@vast.io>"]
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

[dependencies]
common-types = { path = "../types" }
vast-types = "0.8.0"
vastjson = { path = "../../json" }
vasttrie = { package = "patricia-trie-vast", path = "../../util/patricia-trie-vast" }
hash-db = "0.15.0"
itertools = "0.8"
keccak-hash = "0.4.0"
keccak-hasher = { path = "../../util/keccak-hasher" }
kvdb = "0.3.1"
log = "0.4"
vast-bytes = "0.1.0"
rlp = "0.4"
rustc-hex = "1"
serde = { version = "1.0", features = ["derive"] }
trie-db = "0.18.0"
triehash = { package = "triehash-vast", version = "0.2",  path = "../../util/triehash-vast" }

[dev-dependencies]
macros = { path = "../../util/macros" }
