[package]
description = "Vast (VastCore) Light Client Implementation (Block Import IO Service, Blockchain Data Fetching, Light Client Header Chain Storage, Vast Light Protocol (PLP) Provider, Light Transaction Queue, CHT Definitions, Light Client Data Cache), Vast Light Protocol (PLP) Implementation, P2P Network I/O and Event Context Generalization, Peer Error Handling & Punishment, Request Load Timer & Distribution Manager, Pending Request Set Storage, Request Credit Management, Light Client Request Types, Request Chain Builder Utility, On-demand Chain Request Service over LES (for RPCs), ResponseGuard Implementation)"
homepage = "http://vast.io"
license = "GPL-3.0"
name = "vastcore-light"
version = "1.12.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
log = "0.4"
vast-bytes = "0.1"
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
derive_more = "0.14.0"
engine = { path = "../engine" }
vastcore-db = { path = "../db" }
vastcore-blockchain = { path = "../blockchain" }
vast-types = "0.8.0"
executive-state = { path = "../executive-state" }
machine = { path = "../machine" }
memory-db = "0.18.0"
trie-db = "0.18.0"
patricia-trie-vast = { path = "../../util/patricia-trie-vast" }
vastcore-network = { path = "../../util/network" }
vastcore-miner = { path = "../../miner" }
vastcore-io = { path = "../../util/io" }
hash-db = "0.15.0"
vast-util-mem = "0.3.0"
vm = { path = "../vm" }
fastmap = { path = "../../util/fastmap" }
failsafe = { version = "0.3.0", default-features = false, features = ["parking_lot_mutex"] }
rlp = "0.4.0"
rlp_derive = { path = "../../util/rlp-derive" }
smallvec = "0.6"
futures = "0.1"
rand = "0.7"
bincode = "1.1"
serde = "1.0"
serde_derive = "1.0"
spec = { path = "../spec" }
parking_lot = "0.9"
stats = { path = "../../util/stats" }
keccak-hash = "0.4.0"
keccak-hasher = { path = "../../util/keccak-hasher" }
triehash-vast = { version = "0.2",  path = "../../util/triehash-vast" }
kvdb = "0.3.1"
memory-cache = { path = "../../util/memory-cache" }
journaldb = { path = "../../util/journaldb" }
verification = { path = "../verification" }

[dev-dependencies]
vastcore = { path = "..", features = ["test-helpers"] }
kvdb-memorydb = "0.3.1"
tempdir = "0.3"

[features]
default = []
