[package]
description = "Vast state machine"
name = "machine"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]
edition = "2018"
license = "GPL-3.0"

[[bench]]
name = "builtin_contract"
harness = false
required-features = ["test-helpers"]

[dependencies]
account-state = { path = "../account-state" }
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
crossbeam-utils = "0.6"
vastabi = "9.0.1"
vastabi-contract = "9.0.0"
vastabi-derive = "9.0.1"
vastcore-builtin = { path = "../builtin" }
vastcore-call-contract = { path = "../call-contract" }
vastcore-io = { path = "../../util/io" }
vast-types = "0.8.0"
# Used for tests in other crates through the `test-helpers` feature
vastjson = { path = "../../json", optional = true }
evm = { path = "../evm" }
keccak-hash = "0.4.0"
log = "0.4"
lru-cache = "0.1.2"
vast-bytes = "0.1.0"
parking_lot = "0.9"
rlp = "0.4.2"
state-db = { path = "../state-db" }
trace = { path = "../trace" }
trie-vm-factories = { path = "../trie-vm-factories" }
vm = { path = "../vm" }

[dev-dependencies]
common-types = { path = "../types", features = ["test-helpers"] }
criterion = "0.3"
vastcore = { path = "../", features = ["test-helpers"] }
vastcore-io = { path = "../../util/io" }
vastjson = { path = "../../json" }
vast-crypto = { version = "0.4.2", features = ["publickey"] }
macros = { path = "../../util/macros" }
rustc-hex = "1.0"
spec = { path = "../spec" }
tempdir = "0.3"
trace = { path = "../trace" }

[features]
test-helpers = ["vastjson"]
