[package]
name = "vastcore-bloom-journal"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]
description = "Journaling bloom filter"
license = "GPL3"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
siphasher = "0.3"
