[package]
description = "Basic PoA blockchain engine."
name = "basic-authority"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
engine = { path = "../../engine" }
vast-types = "0.8.0"
vastjson = { path = "../../../json" }
vast-crypto = { version = "0.4.2", features = ["publickey"] }
log = "0.4.8"
machine = { path = "../../machine" }
parking_lot = "0.9"
rlp = "0.4.2"
validator-set = { path = "../validator-set" }

[dev-dependencies]
accounts = { package = "vastcore-accounts", path = "../../../accounts" }
engine = { path = "../../engine", features = ["test-helpers"] }
vastcore = { path = "../..", features = ["test-helpers"] }
keccak-hash = "0.4.0"
tempdir = "0.3"
spec = { path = "../../spec" }

[features]
test-helpers = []
