[package]
description = "Vastcore stratum lib"
name = "vastcore-stratum"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
vast-types = "0.8.0"
keccak-hash = "0.4.0"
jsonrpc-core = "14.0.3"
jsonrpc-tcp-server = "14.0.3"
log = "0.4"
parking_lot = "0.9"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"
tokio-io = "0.1"
