[package]
name = "migration-rocksdb"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
log = "0.4"
macros = { path = "../macros" }
kvdb = "0.3.1"
kvdb-rocksdb = "0.4.1"

[dev-dependencies]
tempdir = "0.3"
