[package]
description = "Vast (VastCore) Client & Network Service Creation & Registration with the I/O Subsystem"
name = "vastcore-service"
version = "0.1.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
ansi_term = "0.11"
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
vastcore = { path = ".." }
vastcore-blockchain = { path = "../blockchain" }
vastcore-io = { path = "../../util/io" }
vastcore-private-tx = { path = "../private-tx" }
vastcore-sync = { path = "../sync" }
vast-types = "0.8.0"
kvdb = "0.3.1"
log = "0.4"
snapshot = { path = "../snapshot" }
spec = { path = "../spec" }
trace-time = "0.1"

[dev-dependencies]
vastcore = { path = "..", features = ["test-helpers"] }
vastcore-db = { path = "../db" }
kvdb-rocksdb = "0.4.1"
tempdir = "0.3"
