[package]
description = "Vast Private Transactions"
name = "vastcore-private-tx"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Vast Technologies <admin@vast.io>"]

[dependencies]
account-state = { path = "../account-state" }
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
derive_more = "0.14.0"
vastabi = "9.0.1"
vastabi-contract = "9.0.0"
vastabi-derive = "9.0.1"
vastcore = { path = ".." }
vastcore-db = { path = "../db" }
vastcore-call-contract = { path = "../call-contract" }
vastcore-io = { path = "../../util/io" }
vastcore-miner = { path = "../../miner" }
vast-types = "0.8.0"
vastjson = { path = "../../json" }
fetch = { path = "../../util/fetch" }
futures = "0.1"
vast-util-mem = "0.3.0"
hash-db = "0.15.0"
keccak-hash = "0.4.0"
keccak-hasher = { path = "../../util/keccak-hasher" }
kvdb = "0.3.1"
log = "0.4"
machine = { path = "../machine" }
journaldb = { path = "../../util/journaldb" }
vast-bytes = "0.1"
vast-crypto = { version = "0.4.2", features = ["publickey"] }
parking_lot = "0.9"
trie-db = "0.18.0"
patricia-trie-vast = { path = "../../util/patricia-trie-vast" }
registrar = { path = "../../util/registrar" }
rlp = "0.4.0"
rlp_derive = { path = "../../util/rlp-derive" }
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
spec = { path = "../spec" }
state-db = { path = "../state-db" }
time-utils = { path = "../../util/time-utils" }
tiny-keccak = "1.4"
trace = { path = "../trace" }
transaction-pool = "2.0.1"
url = "2"
vm = { path = "../vm" }

[dev-dependencies]
env_logger = "0.5"
vastcore = { path = "..", features = ["test-helpers"] }
